### ISSUE TITLE
Downloader Class

### ISSUE THREAD

**Issue by sallyishak** [sallyishak/SoftwareConstruction#1]
Zeina Please add your part to the downloader class

**Comment by ZeinaDaghlas** [comment]
Hi Sally as we were open this issue in the last repository , to update you team , Am finalizing the code and will posted after 1 hour

**Comment by ZeinaDaghlas** [comment]
Hello , 

i worked a little bit on the code and try to  track the bug on merge class , i think we have to discuss downloader  class in our next meeting

**Comment by sallyishak** [comment]
yes i added my part
