### ISSUE TITLE
ValidateURL method

### ISSUE THREAD

**Issue by sallyishak** [sallyishak/SoftwareConstruction#2]
Remal, please add the function we have written yesterday to the Parser Class

**Comment by ZeinaDaghlas** [comment]
Hi Sally and Remal .. 
please share the point of reach for this code. I need it to check my classes

**Comment by ZeinaDaghlas** [comment]
Hi Sally and Remal , 

We will close this issue since the bug is solved .
If you have any concern please share it

**Comment by ZeinaDaghlas** [comment]
I will close this issue . 
The problem solved
