### ISSUE TITLE
Problem in Bug tracking tool 

### ISSUE THREAD

**Issue by ZeinaDaghlas** [sallyishak/SoftwareConstruction#3]
We have a problem in bug tracking tool , we opened this issue from 30-12 -2016 
we preferred to re-open the issue in the new repository . 
so team , we reach a point to use ZOHO tool ...

**Comment by remalsaad** [comment]
yes zeina ,I have spent a day searching on bugzeilla and it's not easy to install.
so I suggest to complete with ZOHO later on

**Comment by ZeinaDaghlas** [comment]
We agreed to use netbeans and eclipse debugging tools 

So we will consider this case is closed
